version: "3.6"
services:
  nginx:
    image: nginx
    ports:
      - published: 80
        target: 80
        mode: host
      - published: 443
        target: 443
        mode: host
      - published: 9000
        target: 9000
        mode: host
    volumes:
      - "./single_files/dhparam.pem:/dhparam.pem"
      - "./single_files/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx_conf.d:/etc/nginx/conf.d"
      - "ssl_challenge:/ssl_challenge"
      - "ssl:/ssl"
  mysql:
    image: mysql
    volumes:
      - "./single_files/mysql.cnf:/mysql.cnf"
      - "sql_storage:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: fizz
    entrypoint:
      - /entrypoint.sh
      - "--default-authentication-plugin=mysql_native_password"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    volumes:
      - "./single_files/config.inc.php:/etc/phpmyadmin/config.inc.php"
      - "./single_files/header.twig:/www/templates/login/header.twig"
      - "./single_files/index.php:/www/index.php"
    environment:
      PMA_HOST: mysql
      PMA_PORT: "3306"
    depends_on:
      - mysql
volumes:
  sql_storage: null
  ssl_challenge: null
  ssl: null
